### ISSUE TITLE
Announcing master branch

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#493]
- [x] ~~fix #475~~ (not a bug?)
- [x] merge #472 
- [x] update documentation / migration guide (#498)
- [x] merge #397 
- [x] release/tag new version (#418)
- [x] [announce on ROS discourse](https://discourse.ros.org/t/industrial-ci-rollout-of-version-0-10-0-with-ros2-github-actions-support/13582])
