### ISSUE TITLE
CI consolidation roadmap

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#98]
This issue proposes a roadmap for consolidating `industrial_ci` and [moveit_ci](https://github.com/ros-planning/moveit_ci) as discussed in #75.

Preparations in `industrial_ci`
- [x] cleanup outdated code
- [ ] merge or dismiss all open PRs
- [x] move all scripts except `travis.sh` into `src`of `industrial_ci` package (standard ROS layout)
- [x] split scripts: ci_main.sh (entry point, interface checks, test branching), `tests/source_tests.sh`(default test), 
- [x] factor out code into semantical functions in to-be-sourced scripts
- [x] factor out `$BUILDER == catkin` branches into `builders/catkin.sh` and branch to it from central place
- [x] add support for externally provided tests
- [x] replace `TRAVIS_*`variables by generic ones
- [x] run all tests in docker
- [x] add support for external docker images --> https://github.com/ros-industrial/industrial_ci/pull/116
- [ ] add more unit tests, remove/replace some existing tests for speed-up (#112)
- [x] add `.travis.example.yml` for documentation purposes, `.travis.yml` is for testing the test system..

Until here is just refactoring. These changes do not affect behaviour

Pull in `moveit_ci`, keep history if possible
- [ ] create `fusion` branch
- [x] migrate to `moveit_ci/utils.sh` as it is much cleaner ( includes travis-like folding!), use `ici_` prefix for functions
- [x] add support for `ROS_REPO` (#135, #132))
- [ ] add support for `TEST_BLACKLIST ` (#137)
- [x] integrate `check_clang_format.sh`, add option for clang version
- [x] test with https://github.com/ros-planning/moveit

At this stage all tests should work *as-is* for `moveit_ci` and `industial_ci`, but with `move_it` folding
- [ ] decide new name and location if needed (TBD)
- [ ] make superseded repos use consolidated repo under the hood

New features for consolidated repo:
- [x] introduce `scripts/run_test` with travis-like matrix lines for use without travis
- [ ] release as ROS package (distro-independent?)
- implement additional tests, e.g.:
  - [x] `catkin_lint` (https://github.com/ros-planning/moveit_ci/issues/11) -> Started #219 
  - [ ] sonarqube (#138)
- [x] add support for other CI services (#76, #120)

Usability
- [ ] Show working samples https://github.com/ros-industrial/industrial_ci/issues/105

@130s, @davetcoleman: what do you think?

**Comment by 130s** [comment]
Thanks for putting together!
Easier-to-use is something to think about too. https://github.com/ros-industrial/industrial_ci/issues/105

**Comment by davetcoleman** [comment]
This looks good to me

**Comment by 130s** [comment]
ROS buildfarm testing is not "free" https://github.com/ros/rosdistro/pull/14820#issuecomment-298126877 and we should respect the effort of the maintainers there to minimize the server's cost, so making it easy to utilize online free service (e.g. Travis CI) is still very useful I think.

**Comment by tylerjw** [comment]
>  test with https://github.com/ros-planning/moveit

you can probably check this one off... now that moveit is using industrial_ci (on the master branch for now, open pr's to old ros version branches).
